package com.example.carwash.carwash.utils;

import android.Manifest;
import android.content.Context;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Environment;
import android.support.v4.app.ActivityCompat;

import com.example.carwash.carwash.db.Customer;
import com.example.carwash.carwash.db.CustomerDbHelper;

import java.io.File;
import java.io.FileWriter;
import java.util.Date;
import java.util.Random;

import au.com.bytecode.opencsv.CSVWriter;

/**
 * Created by monageng on 2017/06/02.
 */

public class ExportDatabaseHelper {


    private Context context;

    public ExportDatabaseHelper(Context context) {
        this.context = context;
    }

    public void exportDatabase(String database, File dbFile, String csvFileName, String toEmailAddress) {

           CustomerDbHelper dbhelper = new CustomerDbHelper(context);
           File exportDir = new File(Environment.getExternalStorageDirectory().getAbsoluteFile(), "");
           if (!exportDir.exists())
           {
               exportDir.mkdirs();
           }


           try
           {
               String reportDate = DateUtils.formatToDateString(new Date(), DateUtils.PATTERN_YYYY_MM_DD );
               int i = new Random().nextInt(10);
               File file = new File(exportDir, csvFileName + "_" + reportDate  + i+ ".csv");
               file.createNewFile();
               CSVWriter csvWrite = new CSVWriter(new FileWriter(file));
               SQLiteDatabase db = dbhelper.getReadableDatabase();
               Cursor curCSV = db.rawQuery("SELECT * FROM " + Customer.Entry.TABLE_NAME,null);
               csvWrite.writeNext(curCSV.getColumnNames());
               while(curCSV.moveToNext())
               {
                   //Which column you want to exprort
                   String arrStr[] ={curCSV.getString(0),curCSV.getString(1), curCSV.getString(2),curCSV.getString(3),curCSV.getString(4),curCSV.getString(5), curCSV.getString(6)};
                   csvWrite.writeNext(arrStr);
               }

               csvWrite.close();
               curCSV.close();
               String subject = "Report for  " + reportDate;
               String emailBody = "This is the remote generated by system";
               SendEmail sm = new SendEmail(context, toEmailAddress, subject, emailBody, file.getAbsolutePath());
               try {
                   sm.execute();
               } catch (IllegalStateException e) {
                   String w = e.getMessage();
               }
           }
           catch(Exception sqlEx)
           {
               sqlEx.printStackTrace();
               //Log.e("MainActivity", sqlEx.getMessage(), sqlEx);
           }
    }
}
